name:ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: bilud container
    runs-on: ubuntu-latest
    steps:
     
      - name: check code
        uses: actions/checkout@v3
          with:
          file: ../../Dockerfile
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Build and push
         uses: docker/build-push-action@v2
         with:
          context: .
          push: true
          tags: ahmedtalal/ci:latest
